export const PRODUCT_FETCHED = 'PRODUCT_FETCHED';
export const CARTPRODUCTS_FETCHED = 'CARTPRODUCTS_FETCHED';
export const ADD_CARTPRODUCTS = 'ADD_CARTPRODUCT';
export const REMOVE_CARTPRODUCTS = 'REMOVE_CARTPRODUCTS';
